name: Build a firmware

on:
  workflow_call:
    inputs:
      keyboard:
        type: string
        required: true
      keymap:
        type: string
        required: true

jobs:
  build:
    name: Build a firmware ${{ inputs.keyboard }}:${{ inputs.keymap }}

    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        ref: feature/emacs
        fetch-depth: 1
        submodules: recursive
    - name: Build firmware
      run: qmk compile -j $(nproc) -kb keychron/${{ inputs.keyboard }} -km ${{ inputs.keymap }}
    - name: Archive built firmware
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.keyboard }}-${{ inputs.keymap }}-firmware
        path: ./*.bin
